export const BRUNCH_TOOL_ACTIVITY_LABELS: Readonly<Record<string, string>> = {
  execute_agent_result: 'Running slice agent',
  execute_land_preflight: 'Checking landing readiness',
  execute_launch: 'Checking launch readiness',
  execute_petri_export: 'Exporting Petri artifact',
  execute_plan_draft: 'Drafting execution plan',
  execute_plan_file: 'Compiling execution plan',
  execute_plan_outline: 'Outlining execution plan',
  execute_plan_preview: 'Previewing execution plan',
  execute_populate: 'Populating run worktree',
  execute_promotion_prepare: 'Preparing run promotion',
  execute_replan_abandon_run: 'Abandoning execution run',
  execute_replan_recommendation: 'Diagnosing replan options',
  execute_replan_regenerate_plan: 'Regenerating execution plan',
  execute_replan_retry_current_step: 'Retrying current execution step',
  execute_replan_start_new_run: 'Starting replacement run',
  execute_report_init: 'Initializing run reports',
  execute_run_complete: 'Completing execution run',
  execute_run_create: 'Creating execution run',
  execute_slice_complete: 'Completing execution slice',
  execute_slice_execute: 'Preparing slice execution',
  execute_slice_start: 'Starting execution slice',
  execute_source_copy: 'Copying host source',
  execute_source_policy: 'Recording source policy',
  execute_test_result: 'Verifying slice result',
  execute_worktree_create: 'Creating run worktree',
  mutate_graph: 'Updating specification graph',
  present_alternatives: 'Presenting alternatives',
  read_elicitation_scratchpad: 'Reviewing elicitation scratchpad',
  read_graph: 'Reading specification graph',
  read_reconciliation_needs: 'Reviewing reconciliation needs',
  read_session_context: 'Reading session context',
  read_specification_context: 'Reading specification context',
  read_workspace_context: 'Reading workspace context',
  update_elicitation_scratchpad: 'Updating elicitation scratchpad',
  update_reconciliation_needs: 'Updating reconciliation needs',
  write_worktree_file: 'Writing worktree file',
};

export function resolveBrunchToolActivityLabel(name: string, fallback: string): string {
  return BRUNCH_TOOL_ACTIVITY_LABELS[name] ?? fallback;
}
