CREATE TABLE `elicitation_gaps` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`spec_id` integer NOT NULL,
	`name` text NOT NULL,
	`rationale` text NOT NULL,
	`disposition` text DEFAULT 'open' NOT NULL,
	`basis` text DEFAULT 'explicit' NOT NULL,
	`readiness_band` text NOT NULL,
	`predicate_kind` text NOT NULL,
	`predicate` text NOT NULL,
	`importance` integer DEFAULT 1 NOT NULL,
	`plane_affinity` text,
	`lens_affinity` text,
	`arose_from_gap_id` integer,
	`resolved_by_node_id` integer,
	`created_at_lsn` integer NOT NULL,
	`disposition_set_at_lsn` integer,
	FOREIGN KEY (`spec_id`) REFERENCES `specs`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`arose_from_gap_id`) REFERENCES `elicitation_gaps`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`resolved_by_node_id`) REFERENCES `nodes`(`id`) ON UPDATE no action ON DELETE no action
);
