/**
 * Generated ontology reference — projects the typed graph/schema vocabulary
 * into a runtime-eligible context reference so prompt resources can cite it
 * instead of restating it (D97-L). The typed sources in this directory stay the
 * source of truth (D73-L); the emitted file is never hand-edited.
 *
 * Generates the compact vocabulary tables that prompt resources cite: node
 * kind→band, edge-category policy, required node detail, and inert detail.form
 * payloads.
 *
 * CLI (dev only, run via tsx):
 *   npm run generate:ontology      # write src/agents/contexts/references/graph-ontology.md
 *   npm run check:data-model       # exit non-zero if the committed file is stale
 */

import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import { joinMarkdownBlocks, markdownHeading, markdownTable } from '../../agents/shared/markdown.js';
import { EDGE_CATEGORY_METADATA } from '../policy/category-policy.js';
import { EDGE_CATEGORIES, NODE_KINDS } from './kinds.js';
import {
  bandsForKind,
  claimFormKnownFields,
  CLAIM_FORM_JSON_SCHEMAS,
  NODE_DETAIL_JSON_SCHEMAS,
  NODE_KIND_METADATA,
  nodeDetailForms,
  nodeDetailKnownFields,
  NODE_KINDS_REQUIRING_DETAIL,
  NODE_KINDS_WITH_FORM_DETAIL,
} from './nodes.js';

const SCHEMA_DIR = dirname(fileURLToPath(import.meta.url));
const PROJECT_ROOT = resolve(SCHEMA_DIR, '../../..');

export const GENERATED_ONTOLOGY_PATH = join(PROJECT_ROOT, 'src/agents/contexts/references/graph-ontology.md');

const GENERATED_NOTICE =
  '<!-- @generated by src/graph/schema/generate-ontology-ref.ts — do not edit. Run `npm run generate:ontology`. -->';

function yesNo(value: boolean): string {
  return value ? 'yes' : 'no';
}

function dashWhenEmpty(value: readonly string[]): string {
  return value.length > 0 ? value.join(', ') : '—';
}

export function renderOntologyReference(): string {
  const nodeKindRows = NODE_KINDS.map((kind) => {
    const bands = bandsForKind(kind);
    return [kind, NODE_KIND_METADATA[kind].label, dashWhenEmpty(bands)];
  });

  const edgeCategoryRows = EDGE_CATEGORIES.map((category) => {
    const metadata = EDGE_CATEGORY_METADATA[category];
    return [
      category,
      `${metadata.sourceRole} → ${metadata.targetRole}`,
      metadata.affected ?? '—',
      metadata.impactKind,
      metadata.stanceRequired ? 'required' : '—',
      yesNo(metadata.criteriaHelpSignal),
      metadata.projectionEffect,
    ];
  });

  const requiredDetailRows = NODE_KINDS_REQUIRING_DETAIL.map((kind) => [
    kind,
    NODE_DETAIL_JSON_SCHEMAS[kind].description as string,
    nodeDetailKnownFields(kind).join(', '),
  ]);

  const allowedFormRows = NODE_KINDS_WITH_FORM_DETAIL.map((kind) => [kind, nodeDetailForms(kind).join(', ')]);

  const formPayloadRows = Object.keys(CLAIM_FORM_JSON_SCHEMAS).map((form) => [
    form,
    CLAIM_FORM_JSON_SCHEMAS[form as keyof typeof CLAIM_FORM_JSON_SCHEMAS].description as string,
    claimFormKnownFields(form as keyof typeof CLAIM_FORM_JSON_SCHEMAS).join(', '),
  ]);

  return `${joinMarkdownBlocks(
    GENERATED_NOTICE,
    markdownHeading(1, 'Graph ontology reference'),
    'Projected from `src/graph/schema/kinds.ts`, `nodes.ts`, and `graph/policy/category-policy.ts` — the source of truth for graph vocabulary and edge policy (D73-L). Regenerate with `npm run generate:ontology`; drift is caught by `npm run check:data-model`. Do not hand-edit.',
    markdownHeading(3, 'Node kind → readiness band'),
    'Kinds appear in canonical plane order (intent, oracle, design, plan). A band cell of `—` means the kind carries no readiness band (D94-L).',
    markdownTable([['Kind', 'Code', 'Readiness bands'], ...nodeKindRows]),
    markdownHeading(3, 'Edge category policy'),
    'Role-named endpoints are the fields authors use in `mutate_graph`; impact and projection flags come from edge-category metadata, not storage direction (D51-L/D87-L).',
    markdownTable([
      [
        'Category',
        'Endpoint roles',
        'Affected endpoint',
        'Impact strength',
        'Stance',
        'Criteria help?',
        'Projection effect',
      ],
      ...edgeCategoryRows,
    ]),
    markdownHeading(3, 'Node detail payloads'),
    'Only these node kinds require non-form detail payloads. Other per-kind behavior comes from `kind`, not detail shape (D54-L/D88-L).',
    markdownTable([['Kind', 'Payload', 'Fields'], ...requiredDetailRows]),
    markdownHeading(3, 'Claim detail.form payloads'),
    '`kind` drives graph behavior; `detail.form` is inert method payload plus a renderer hook (D88-L).',
    markdownTable([['Kind', 'Allowed forms'], ...allowedFormRows]),
    markdownTable([['Form', 'Payload', 'Fields'], ...formPayloadRows]),
  )}\n`;
}

function runCli(argv: readonly string[]): number {
  const next = renderOntologyReference();

  if (argv.includes('--check')) {
    let current = '';
    try {
      current = readFileSync(GENERATED_ONTOLOGY_PATH, 'utf8');
    } catch {
      current = '';
    }
    if (current !== next) {
      console.error('ontology reference is stale or missing; run `npm run generate:ontology`');
      return 1;
    }
    console.log('ontology reference in sync with typed sources');
    return 0;
  }

  mkdirSync(dirname(GENERATED_ONTOLOGY_PATH), { recursive: true });
  writeFileSync(GENERATED_ONTOLOGY_PATH, next);
  console.log(`wrote ${GENERATED_ONTOLOGY_PATH}`);
  return 0;
}

if (import.meta.url === `file://${process.argv[1]}`) {
  process.exitCode = runCli(process.argv.slice(2));
}
