/**
 * Generated ontology reference — projects the typed graph/schema vocabulary
 * into a runtime-eligible context reference so prompt resources can cite it
 * instead of restating it (D97-L). The typed sources in this directory stay the
 * source of truth (D73-L); the emitted file is never hand-edited.
 *
 * This slice generates only the kind→band table; further vocabulary tables
 * (edge categories, detail forms) are added when a concrete citing need appears,
 * not speculatively.
 *
 * CLI (dev only, run via tsx):
 *   npm run generate:ontology      # write src/agents/contexts/references/graph-ontology.md
 *   npm run check:data-model       # exit non-zero if the committed file is stale
 */

import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import {
  joinMarkdownBlocks,
  markdownHeading,
  markdownTable,
} from '../../agents/contexts/primitives/markdown.js';
import { NODE_KINDS } from './kinds.js';
import { bandsForKind, NODE_KIND_METADATA } from './nodes.js';

const SCHEMA_DIR = dirname(fileURLToPath(import.meta.url));
const PROJECT_ROOT = resolve(SCHEMA_DIR, '../../..');

export const GENERATED_ONTOLOGY_PATH = join(PROJECT_ROOT, 'src/agents/contexts/references/graph-ontology.md');

const GENERATED_NOTICE =
  '<!-- @generated by src/graph/schema/generate-ontology-ref.ts — do not edit. Run `npm run generate:ontology`. -->';

export function renderOntologyReference(): string {
  const rows = NODE_KINDS.map((kind) => {
    const bands = bandsForKind(kind);
    const cell = bands.length > 0 ? bands.join(', ') : '—';
    return [kind, NODE_KIND_METADATA[kind].label, cell];
  });

  return `${joinMarkdownBlocks(
    GENERATED_NOTICE,
    markdownHeading(1, 'Graph ontology reference'),
    'Projected from `src/graph/schema/kinds.ts` and `nodes.ts` — the source of truth for graph vocabulary (D73-L). Regenerate with `npm run generate:ontology`; drift is caught by `npm run check:data-model`. Do not hand-edit.',
    markdownHeading(3, 'Node kind → readiness band'),
    'Kinds appear in canonical plane order (intent, oracle, design, plan). A band cell of `—` means the kind carries no readiness band (D94-L).',
    markdownTable([['Kind', 'Code', 'Readiness bands'], ...rows]),
  )}\n`;
}

function runCli(argv: readonly string[]): number {
  const next = renderOntologyReference();

  if (argv.includes('--check')) {
    let current = '';
    try {
      current = readFileSync(GENERATED_ONTOLOGY_PATH, 'utf8');
    } catch {
      current = '';
    }
    if (current !== next) {
      console.error('ontology reference is stale or missing; run `npm run generate:ontology`');
      return 1;
    }
    console.log('ontology reference in sync with typed sources');
    return 0;
  }

  mkdirSync(dirname(GENERATED_ONTOLOGY_PATH), { recursive: true });
  writeFileSync(GENERATED_ONTOLOGY_PATH, next);
  console.log(`wrote ${GENERATED_ONTOLOGY_PATH}`);
  return 0;
}

if (import.meta.url === `file://${process.argv[1]}`) {
  process.exitCode = runCli(process.argv.slice(2));
}
