import { readFileSync } from 'node:fs';

import { describe, expect, it } from 'vitest';

import { EDGE_CATEGORY_METADATA } from '../../policy/category-policy.js';
import { GENERATED_ONTOLOGY_PATH, renderOntologyReference } from '../generate-ontology-ref.js';

const projectRoot = new URL('../../../../', import.meta.url).pathname;
const expectedReferencePath = `${projectRoot}src/agents/contexts/references/graph-ontology.md`;
const nodesSourcePath = `${projectRoot}src/graph/schema/nodes.ts`;
import { EDGE_CATEGORIES, NODE_KINDS } from '../kinds.js';
import {
  bandsForKind,
  CLAIM_FORM_JSON_SCHEMAS,
  NODE_DETAIL_FORMS,
  NODE_DETAIL_JSON_SCHEMAS,
} from '../nodes.js';

describe('ontology reference generator', () => {
  const markdown = renderOntologyReference();
  const rows = markdown.split('\n').filter((line) => line.startsWith('| '));

  it('lists every node kind with its exact bands from the typed source', () => {
    for (const kind of NODE_KINDS) {
      const bands = bandsForKind(kind);
      const expected = bands.length > 0 ? bands.join(', ') : '—';
      const row = rows.find((line) => line.startsWith(`| ${kind} |`));
      expect(row, `row for kind ${kind}`).toBeDefined();
      expect(row).toContain(expected);
    }
  });

  it('writes the runtime-eligible context reference path', () => {
    expect(GENERATED_ONTOLOGY_PATH).toBe(expectedReferencePath);
  });

  it('renders the reference in the shared context-reference shape', () => {
    expect(markdown).toContain('@generated by src/graph/schema/generate-ontology-ref.ts');
    expect(markdown.split('\n')).toContain('### Node kind → readiness band');
    expect(markdown.split('\n')).toContain('### Edge category policy');
    expect(markdown.split('\n')).toContain('### Node detail payloads');
    expect(markdown.split('\n')).toContain('### Claim detail.form payloads');
    expect(markdown.split('\n')).not.toContain('## Node kind → readiness band');
    expect(markdown).toContain('Kinds appear in canonical plane order');
    expect(markdown).toContain(
      '`kind` drives graph behavior; `detail.form` is inert method payload plus a renderer hook (D88-L).',
    );
  });

  it('lists every edge category with role-named endpoints and policy flags from the typed source', () => {
    for (const category of EDGE_CATEGORIES) {
      const metadata = EDGE_CATEGORY_METADATA[category];
      const row = rows.find((line) => line.startsWith(`| ${category} |`));
      expect(row, `row for edge category ${category}`).toBeDefined();
      expect(row).toContain(`${metadata.sourceRole} → ${metadata.targetRole}`);
      expect(row).toContain(metadata.affected ?? '—');
      expect(row).toContain(metadata.impactKind);
      expect(row).toContain(metadata.stanceRequired ? 'required' : '—');
      expect(row).toContain(metadata.criteriaHelpSignal ? 'yes' : 'no');
      expect(row).toContain(metadata.projectionEffect);
    }
  });

  it('lists required detail kinds and allowed detail.form payload fields from the typed source', () => {
    for (const [kind, schema] of Object.entries(NODE_DETAIL_JSON_SCHEMAS)) {
      const expectedFields = Object.keys(schema.properties).join(', ');
      const row = rows.find((line) => line.startsWith(`| ${kind} |`) && line.includes(expectedFields));
      expect(row, `required detail row for ${kind}`).toBeDefined();
    }

    for (const [kind, forms] of Object.entries(NODE_DETAIL_FORMS)) {
      const expectedForms = forms.join(', ');
      const row = rows.find((line) => line.startsWith(`| ${kind} |`) && line.includes(expectedForms));
      expect(row, `detail.form row for ${kind}`).toBeDefined();
    }

    for (const [form, schema] of Object.entries(CLAIM_FORM_JSON_SCHEMAS)) {
      const expectedFields = Object.keys(schema.properties).join(', ');
      const row = rows.find((line) => line.startsWith(`| ${form} |`) && line.includes(expectedFields));
      expect(row, `form row for ${form}`).toBeDefined();
    }
  });

  it('keeps the Gherkin then field owned by one plain schema constant', () => {
    const source = readFileSync(nodesSourcePath, 'utf8');
    const gherkinSchema = CLAIM_FORM_JSON_SCHEMAS.gherkin;

    expect(gherkinSchema.required).toEqual([
      'form',
      ...Object.keys(gherkinSchema.properties).filter((key) => key === 'then'),
    ]);
    expect(source).toContain("const GHERKIN_THEN_FIELD = 'then';");
    expect(source).toContain("required: ['form', GHERKIN_THEN_FIELD]");
  });

  it('keeps the committed generated file in sync with the typed source (drift guard)', () => {
    const committed = readFileSync(GENERATED_ONTOLOGY_PATH, 'utf8');
    expect(committed).toBe(markdown);
  });
});
