import { readFileSync } from 'node:fs';

import { describe, expect, it } from 'vitest';

import { GENERATED_ONTOLOGY_PATH, renderOntologyReference } from '../generate-ontology-ref.js';

const projectRoot = new URL('../../../../', import.meta.url).pathname;
const expectedReferencePath = `${projectRoot}src/agents/contexts/references/graph-ontology.md`;
import { NODE_KINDS } from '../kinds.js';
import { bandsForKind } from '../nodes.js';

describe('ontology reference generator', () => {
  const markdown = renderOntologyReference();
  const rows = markdown.split('\n').filter((line) => line.startsWith('| '));

  it('lists every node kind with its exact bands from the typed source', () => {
    for (const kind of NODE_KINDS) {
      const bands = bandsForKind(kind);
      const expected = bands.length > 0 ? bands.join(', ') : '—';
      const row = rows.find((line) => line.startsWith(`| ${kind} |`));
      expect(row, `row for kind ${kind}`).toBeDefined();
      expect(row).toContain(expected);
    }
  });

  it('writes the runtime-eligible context reference path', () => {
    expect(GENERATED_ONTOLOGY_PATH).toBe(expectedReferencePath);
  });

  it('renders the reference in the shared context-reference shape', () => {
    expect(markdown).toContain('@generated by src/graph/schema/generate-ontology-ref.ts');
    expect(markdown.split('\n')).toContain('### Node kind → readiness band');
    expect(markdown.split('\n')).not.toContain('## Node kind → readiness band');
    expect(markdown).toContain('Kinds appear in canonical plane order');
  });

  it('keeps the committed generated file in sync with the typed source (drift guard)', () => {
    const committed = readFileSync(GENERATED_ONTOLOGY_PATH, 'utf8');
    expect(committed).toBe(markdown);
  });
});
