import type { PetriNet, Scenario } from "./model"

const laneY = {
  mechanical: 80,
  oracle: 210,
  design: 340,
  semantic: 470,
  revision: 600,
} as const

export const sliceNet: PetriNet = {
  places: [
    {
      id: "p_slice_selected",
      label: "Slice selected",
      lane: "mechanical",
      description: "The active plan slice has been chosen for orchestration.",
      tokenLabel: "P1",
      semanticRef: "plan_node P1",
      x: 40,
      y: laneY.mechanical,
    },
    {
      id: "p_context_ready",
      label: "Context pack ready",
      lane: "mechanical",
      description: "A bounded context pack has been generated from the current workspace graph.",
      tokenLabel: "G42",
      semanticRef: "contextPackRef + graphRevision",
      x: 230,
      y: laneY.mechanical,
    },
    {
      id: "p_code_ready",
      label: "Code artifact ready",
      lane: "mechanical",
      description: "Implementation artifacts exist. This is mechanical progress, not semantic completion.",
      tokenLabel: "artifact",
      x: 430,
      y: laneY.mechanical,
    },
    {
      id: "p_verify_passed",
      label: "Verify passed",
      lane: "mechanical",
      description: "The inner/gate verification command passed for the artifact.",
      tokenLabel: "report",
      x: 630,
      y: laneY.mechanical,
    },
    {
      id: "p_oracle_required",
      label: "Oracle required",
      lane: "oracle",
      description: "The plan graph has a gating oracle relation for this slice.",
      tokenLabel: "O1",
      semanticRef: "plan.verified_by_oracle P1 -> O1",
      x: 230,
      y: laneY.oracle,
    },
    {
      id: "p_oracle_evidence",
      label: "Oracle evidence ready",
      lane: "oracle",
      description: "A report or artifact is available that can be assessed against the oracle check.",
      tokenLabel: "evidence",
      x: 430,
      y: laneY.oracle,
    },
    {
      id: "p_oracle_satisfied",
      label: "Oracle satisfied",
      lane: "oracle",
      description: "Judgment-bearing token: evidence satisfies the required oracle check for this graph revision.",
      tokenLabel: "O1 ✓",
      x: 630,
      y: laneY.oracle,
    },
    {
      id: "p_design_required",
      label: "Design target required",
      lane: "design",
      description: "The plan graph says this slice must introduce or exercise a design node.",
      tokenLabel: "D2",
      semanticRef: "plan.exercises_design P1 -> D2",
      x: 230,
      y: laneY.design,
    },
    {
      id: "p_design_evidence",
      label: "Design evidence ready",
      lane: "design",
      description: "Evidence exists that can be reviewed for whether the intended seam/module was exercised.",
      tokenLabel: "trace",
      x: 430,
      y: laneY.design,
    },
    {
      id: "p_design_exercised",
      label: "Design exercised",
      lane: "design",
      description: "Judgment-bearing token: the implementation actually crossed the intended design seam.",
      tokenLabel: "D2 ✓",
      x: 630,
      y: laneY.design,
    },
    {
      id: "p_intent_current",
      label: "Intent current",
      lane: "semantic",
      description: "The targeted intent nodes are still current for the graph revision used by the work.",
      tokenLabel: "R1/C1",
      semanticRef: "plan.establishes_intent P1 -> R1",
      x: 230,
      y: laneY.semantic,
    },
    {
      id: "p_intent_established",
      label: "Intent established",
      lane: "semantic",
      description: "Judgment-bearing token: required intent targets are established by the evidence bundle.",
      tokenLabel: "intent ✓",
      x: 630,
      y: laneY.semantic,
    },
    {
      id: "p_completion_accepted",
      label: "Completion accepted",
      lane: "semantic",
      description: "A reviewer or trusted assessment accepts that the plan claim is semantically complete.",
      tokenLabel: "claim ✓",
      x: 820,
      y: laneY.semantic,
    },
    {
      id: "p_plan_done",
      label: "Plan done accepted",
      lane: "semantic",
      description: "Terminal semantic marking. This can support declaring plan execution status done.",
      tokenLabel: "done",
      semanticRef: "plan_node.executionStatus = done candidate",
      x: 1020,
      y: laneY.semantic,
    },
    {
      id: "p_graph_current",
      label: "Graph revision current",
      lane: "revision",
      description: "The evidence and context pack are still aligned with the current workspace graph revision.",
      tokenLabel: "G42 current",
      x: 40,
      y: laneY.revision,
    },
    {
      id: "p_graph_stale",
      label: "Graph stale",
      lane: "revision",
      description: "The context/evidence was produced from an older graph revision and needs reconciliation.",
      tokenLabel: "G42 stale",
      x: 230,
      y: laneY.revision,
    },
    {
      id: "p_risk_resolved",
      label: "Risk resolved / accepted",
      lane: "revision",
      description: "Residual risks are either retired by evidence or explicitly accepted/deferred.",
      tokenLabel: "risk ✓",
      semanticRef: "plan.retires_risk or accepted residual risk",
      x: 820,
      y: laneY.revision,
    },
  ],
  transitions: [
    {
      id: "t_build_context",
      label: "Build context",
      lane: "mechanical",
      description: "Compile the active plan slice and graph neighborhood into an execution context pack.",
      x: 135,
      y: laneY.mechanical,
    },
    {
      id: "t_implement",
      label: "Implement",
      lane: "mechanical",
      description: "Dispatch coding work using the context pack.",
      x: 330,
      y: laneY.mechanical,
    },
    {
      id: "t_verify",
      label: "Run verify",
      lane: "mechanical",
      description: "Run tests/checks that produce mechanical evidence.",
      x: 530,
      y: laneY.mechanical,
    },
    {
      id: "t_collect_oracle_evidence",
      label: "Collect oracle evidence",
      lane: "oracle",
      description: "Route verification output into evidence for the required oracle check.",
      compiledFrom: ["plan.verified_by_oracle P1 -> O1"],
      x: 330,
      y: laneY.oracle,
    },
    {
      id: "t_assess_oracle",
      label: "Assess oracle",
      lane: "oracle",
      description: "Decide whether the evidence satisfies the required oracle check.",
      guard: "Evidence maps to O1, report passes, and graph revision is current.",
      compiledFrom: ["plan.verified_by_oracle P1 -> O1"],
      x: 530,
      y: laneY.oracle,
    },
    {
      id: "t_collect_design_evidence",
      label: "Collect design evidence",
      lane: "design",
      description: "Produce evidence about whether the implementation crossed the intended seam/module.",
      compiledFrom: ["plan.exercises_design P1 -> D2"],
      x: 330,
      y: laneY.design,
    },
    {
      id: "t_assess_design",
      label: "Assess design",
      lane: "design",
      description: "Judge whether the design node was actually introduced or exercised.",
      guard: "Evidence shows the intended design seam D2 was exercised, not bypassed.",
      compiledFrom: ["plan.exercises_design P1 -> D2"],
      x: 530,
      y: laneY.design,
    },
    {
      id: "t_assess_intent",
      label: "Assess intent",
      lane: "semantic",
      description: "Judge whether oracle and design evidence establish the intent target.",
      guard: "Intent target is current; required oracle/design tokens are present.",
      compiledFrom: ["plan.establishes_intent P1 -> R1"],
      x: 530,
      y: laneY.semantic,
    },
    {
      id: "t_review_completion",
      label: "Review completion",
      lane: "semantic",
      description: "Accept the semantic completion claim after evidence and residual risk review.",
      x: 725,
      y: laneY.semantic,
    },
    {
      id: "t_declare_done",
      label: "Declare done",
      lane: "semantic",
      description: "Terminal transition: declare or suggest that the plan node is done.",
      guard: "All gating semantic tokens are present and graph revision remains current.",
      x: 920,
      y: laneY.semantic,
    },
    {
      id: "t_detect_stale",
      label: "Detect stale graph",
      lane: "revision",
      description: "Detect that artifacts/evidence were produced from a stale graph revision.",
      x: 135,
      y: laneY.revision,
    },
  ],
  arcs: [
    { id: "a1", source: "p_slice_selected", target: "t_build_context" },
    { id: "a2", source: "p_graph_current", target: "t_build_context" },
    { id: "a3", source: "t_build_context", target: "p_context_ready" },
    { id: "a4", source: "p_context_ready", target: "t_implement" },
    { id: "a5", source: "t_implement", target: "p_code_ready" },
    { id: "a6", source: "p_code_ready", target: "t_verify" },
    { id: "a7", source: "t_verify", target: "p_verify_passed" },
    { id: "a8", source: "p_oracle_required", target: "t_collect_oracle_evidence" },
    { id: "a9", source: "p_verify_passed", target: "t_collect_oracle_evidence" },
    { id: "a10", source: "t_collect_oracle_evidence", target: "p_oracle_evidence" },
    { id: "a11", source: "p_oracle_evidence", target: "t_assess_oracle" },
    { id: "a12", source: "p_graph_current", target: "t_assess_oracle" },
    { id: "a13", source: "t_assess_oracle", target: "p_oracle_satisfied" },
    { id: "a14", source: "p_design_required", target: "t_collect_design_evidence" },
    { id: "a15", source: "p_code_ready", target: "t_collect_design_evidence" },
    { id: "a16", source: "t_collect_design_evidence", target: "p_design_evidence" },
    { id: "a17", source: "p_design_evidence", target: "t_assess_design" },
    { id: "a18", source: "t_assess_design", target: "p_design_exercised" },
    { id: "a19", source: "p_intent_current", target: "t_assess_intent" },
    { id: "a20", source: "p_oracle_satisfied", target: "t_assess_intent" },
    { id: "a21", source: "p_design_exercised", target: "t_assess_intent" },
    { id: "a22", source: "t_assess_intent", target: "p_intent_established" },
    { id: "a23", source: "p_intent_established", target: "t_review_completion" },
    { id: "a24", source: "p_risk_resolved", target: "t_review_completion" },
    { id: "a25", source: "t_review_completion", target: "p_completion_accepted" },
    { id: "a26", source: "p_verify_passed", target: "t_declare_done" },
    { id: "a27", source: "p_oracle_satisfied", target: "t_declare_done" },
    { id: "a28", source: "p_design_exercised", target: "t_declare_done" },
    { id: "a29", source: "p_intent_established", target: "t_declare_done" },
    { id: "a30", source: "p_completion_accepted", target: "t_declare_done" },
    { id: "a31", source: "p_graph_current", target: "t_declare_done" },
    { id: "a32", source: "t_declare_done", target: "p_plan_done" },
    { id: "a33", source: "p_context_ready", target: "t_detect_stale" },
    { id: "a34", source: "t_detect_stale", target: "p_graph_stale" },
  ],
}

const baseFired = new Set([
  "t_build_context",
  "t_implement",
  "t_verify",
  "t_collect_oracle_evidence",
  "t_assess_oracle",
  "t_collect_design_evidence",
  "t_assess_design",
  "t_assess_intent",
  "t_review_completion",
])

export const scenarios: Scenario[] = [
  {
    id: "happy",
    label: "Happy path",
    headline: "Mechanical evidence and semantic gates converge.",
    summary:
      "The slice reaches verification, satisfies its oracle, exercises the design seam, establishes intent, resolves risk, and can declare plan-done.",
    valueProbe:
      "Shows the desirable end state: Petri orchestration is not just task flow, but evidence-gated semantic completion.",
    marking: new Set([
      "p_slice_selected",
      "p_graph_current",
      "p_context_ready",
      "p_code_ready",
      "p_verify_passed",
      "p_oracle_required",
      "p_oracle_evidence",
      "p_oracle_satisfied",
      "p_design_required",
      "p_design_evidence",
      "p_design_exercised",
      "p_intent_current",
      "p_intent_established",
      "p_risk_resolved",
      "p_completion_accepted",
      "p_plan_done",
    ]),
    firedTransitions: new Set([...baseFired, "t_declare_done"]),
    notesById: {},
  },
  {
    id: "missing-oracle",
    label: "Missing oracle",
    headline: "Implementation can finish while semantic completion remains blocked.",
    summary:
      "Code and verify pass, but no oracle requirement/evidence token exists. The plan cannot become semantically done even though mechanical work looks green.",
    valueProbe:
      "Tests whether the UI can explain why green CI is insufficient: the required graph-derived oracle was not satisfied.",
    marking: new Set([
      "p_slice_selected",
      "p_graph_current",
      "p_context_ready",
      "p_code_ready",
      "p_verify_passed",
      "p_design_required",
      "p_design_evidence",
      "p_design_exercised",
      "p_intent_current",
      "p_risk_resolved",
    ]),
    firedTransitions: new Set(["t_build_context", "t_implement", "t_verify", "t_collect_design_evidence", "t_assess_design"]),
    notesById: {
      p_oracle_required: "No accepted oracle edge compiled into this run, or O1 is not implemented yet.",
      t_declare_done: "Blocked despite VerifyPassed: OracleSatisfied is missing.",
    },
  },
  {
    id: "design-bypass",
    label: "Design bypass",
    headline: "Tests pass, but the intended seam was not exercised.",
    summary:
      "Mechanical verification and oracle evidence are present, but design assessment rejects the implementation because it bypassed the design node the slice was meant to prove.",
    valueProbe:
      "Surfaces architectural value: orchestration can protect design intent, not merely run tests.",
    marking: new Set([
      "p_slice_selected",
      "p_graph_current",
      "p_context_ready",
      "p_code_ready",
      "p_verify_passed",
      "p_oracle_required",
      "p_oracle_evidence",
      "p_oracle_satisfied",
      "p_design_required",
      "p_design_evidence",
      "p_intent_current",
      "p_risk_resolved",
    ]),
    firedTransitions: new Set([
      "t_build_context",
      "t_implement",
      "t_verify",
      "t_collect_oracle_evidence",
      "t_assess_oracle",
      "t_collect_design_evidence",
    ]),
    notesById: {
      p_design_exercised: "Assessment rejected: evidence did not show the intended seam D2 was crossed.",
      t_assess_design: "Guard failed: implementation bypassed D2.",
    },
  },
  {
    id: "stale-graph",
    label: "Stale graph",
    headline: "Long-running work cannot complete against an obsolete semantic revision.",
    summary:
      "Context and artifacts exist, but the graph advanced during execution. Semantic transitions that require GraphRevisionCurrent are blocked until reconciliation or rebuild.",
    valueProbe:
      "Tests whether Petri orchestration can make stale-context hazards visible instead of silently accepting outdated work.",
    marking: new Set([
      "p_slice_selected",
      "p_context_ready",
      "p_code_ready",
      "p_verify_passed",
      "p_oracle_required",
      "p_oracle_evidence",
      "p_design_required",
      "p_design_evidence",
      "p_design_exercised",
      "p_intent_current",
      "p_risk_resolved",
      "p_graph_stale",
    ]),
    firedTransitions: new Set([
      "t_build_context",
      "t_implement",
      "t_verify",
      "t_collect_oracle_evidence",
      "t_collect_design_evidence",
      "t_assess_design",
      "t_detect_stale",
    ]),
    notesById: {
      p_graph_current: "Missing because current graph is G43 while context/evidence was produced from G42.",
      t_assess_oracle: "Blocked: oracle assessment requires current graph revision.",
      t_declare_done: "Blocked: PlanDoneAccepted cannot be produced from stale evidence.",
    },
  },
  {
    id: "risk-pending",
    label: "Risk pending",
    headline: "All evidence passes, but residual risk still needs explicit treatment.",
    summary:
      "Intent, oracle, and design gates are satisfied. Completion review is blocked because a residual risk is neither retired nor explicitly accepted/deferred.",
    valueProbe:
      "Tests whether the net can represent judgment work that is not reducible to tests or code artifacts.",
    marking: new Set([
      "p_slice_selected",
      "p_graph_current",
      "p_context_ready",
      "p_code_ready",
      "p_verify_passed",
      "p_oracle_required",
      "p_oracle_evidence",
      "p_oracle_satisfied",
      "p_design_required",
      "p_design_evidence",
      "p_design_exercised",
      "p_intent_current",
      "p_intent_established",
    ]),
    firedTransitions: new Set([
      "t_build_context",
      "t_implement",
      "t_verify",
      "t_collect_oracle_evidence",
      "t_assess_oracle",
      "t_collect_design_evidence",
      "t_assess_design",
      "t_assess_intent",
    ]),
    notesById: {
      p_risk_resolved: "Residual risk is still open. A human/agent must retire it or explicitly accept/defer it.",
      t_review_completion: "Blocked: completion review requires risk treatment.",
    },
  },
]
