/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './file-routes/__root'
import { Route as IndexRouteImport } from './file-routes/index'
import { Route as ProjectIdRouteImport } from './file-routes/project.$id'
import { Route as ProjectIdKnowledgeRouteImport } from './file-routes/project_.$id.knowledge'
import { Route as ProjectIdExportRouteImport } from './file-routes/project_.$id.export'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectIdRoute = ProjectIdRouteImport.update({
  id: '/project/$id',
  path: '/project/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectIdKnowledgeRoute = ProjectIdKnowledgeRouteImport.update({
  id: '/project_/$id/knowledge',
  path: '/project/$id/knowledge',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectIdExportRoute = ProjectIdExportRouteImport.update({
  id: '/project_/$id/export',
  path: '/project/$id/export',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/project/$id': typeof ProjectIdRoute
  '/project/$id/export': typeof ProjectIdExportRoute
  '/project/$id/knowledge': typeof ProjectIdKnowledgeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/project/$id': typeof ProjectIdRoute
  '/project/$id/export': typeof ProjectIdExportRoute
  '/project/$id/knowledge': typeof ProjectIdKnowledgeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/project/$id': typeof ProjectIdRoute
  '/project_/$id/export': typeof ProjectIdExportRoute
  '/project_/$id/knowledge': typeof ProjectIdKnowledgeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/project/$id'
    | '/project/$id/export'
    | '/project/$id/knowledge'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/project/$id' | '/project/$id/export' | '/project/$id/knowledge'
  id:
    | '__root__'
    | '/'
    | '/project/$id'
    | '/project_/$id/export'
    | '/project_/$id/knowledge'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProjectIdRoute: typeof ProjectIdRoute
  ProjectIdExportRoute: typeof ProjectIdExportRoute
  ProjectIdKnowledgeRoute: typeof ProjectIdKnowledgeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project/$id': {
      id: '/project/$id'
      path: '/project/$id'
      fullPath: '/project/$id'
      preLoaderRoute: typeof ProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project_/$id/knowledge': {
      id: '/project_/$id/knowledge'
      path: '/project/$id/knowledge'
      fullPath: '/project/$id/knowledge'
      preLoaderRoute: typeof ProjectIdKnowledgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project_/$id/export': {
      id: '/project_/$id/export'
      path: '/project/$id/export'
      fullPath: '/project/$id/export'
      preLoaderRoute: typeof ProjectIdExportRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProjectIdRoute: ProjectIdRoute,
  ProjectIdExportRoute: ProjectIdExportRoute,
  ProjectIdKnowledgeRoute: ProjectIdKnowledgeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
