/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SpecificationIdRouteRouteImport } from './routes/specification/$id/route'
import { Route as SpecificationIdIndexRouteImport } from './routes/specification/$id/index'
import { Route as SpecificationIdExportRouteImport } from './routes/specification/$id/export'
import { Route as SpecificationIdViewRouteRouteImport } from './routes/specification/$id/_view/route'
import { Route as SpecificationIdViewRequirementsReviewRouteImport } from './routes/specification/$id/_view/requirements-review'
import { Route as SpecificationIdViewGroundingRouteImport } from './routes/specification/$id/_view/grounding'
import { Route as SpecificationIdViewElicitationRouteImport } from './routes/specification/$id/_view/elicitation'
import { Route as SpecificationIdViewAcceptanceReviewRouteImport } from './routes/specification/$id/_view/acceptance-review'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SpecificationIdRouteRoute = SpecificationIdRouteRouteImport.update({
  id: '/specification/$id',
  path: '/specification/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SpecificationIdIndexRoute = SpecificationIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SpecificationIdRouteRoute,
} as any)
const SpecificationIdExportRoute = SpecificationIdExportRouteImport.update({
  id: '/export',
  path: '/export',
  getParentRoute: () => SpecificationIdRouteRoute,
} as any)
const SpecificationIdViewRouteRoute =
  SpecificationIdViewRouteRouteImport.update({
    id: '/_view',
    getParentRoute: () => SpecificationIdRouteRoute,
  } as any)
const SpecificationIdViewRequirementsReviewRoute =
  SpecificationIdViewRequirementsReviewRouteImport.update({
    id: '/requirements-review',
    path: '/requirements-review',
    getParentRoute: () => SpecificationIdViewRouteRoute,
  } as any)
const SpecificationIdViewGroundingRoute =
  SpecificationIdViewGroundingRouteImport.update({
    id: '/grounding',
    path: '/grounding',
    getParentRoute: () => SpecificationIdViewRouteRoute,
  } as any)
const SpecificationIdViewElicitationRoute =
  SpecificationIdViewElicitationRouteImport.update({
    id: '/elicitation',
    path: '/elicitation',
    getParentRoute: () => SpecificationIdViewRouteRoute,
  } as any)
const SpecificationIdViewAcceptanceReviewRoute =
  SpecificationIdViewAcceptanceReviewRouteImport.update({
    id: '/acceptance-review',
    path: '/acceptance-review',
    getParentRoute: () => SpecificationIdViewRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/specification/$id': typeof SpecificationIdViewRouteRouteWithChildren
  '/specification/$id/export': typeof SpecificationIdExportRoute
  '/specification/$id/': typeof SpecificationIdIndexRoute
  '/specification/$id/acceptance-review': typeof SpecificationIdViewAcceptanceReviewRoute
  '/specification/$id/elicitation': typeof SpecificationIdViewElicitationRoute
  '/specification/$id/grounding': typeof SpecificationIdViewGroundingRoute
  '/specification/$id/requirements-review': typeof SpecificationIdViewRequirementsReviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/specification/$id': typeof SpecificationIdIndexRoute
  '/specification/$id/export': typeof SpecificationIdExportRoute
  '/specification/$id/acceptance-review': typeof SpecificationIdViewAcceptanceReviewRoute
  '/specification/$id/elicitation': typeof SpecificationIdViewElicitationRoute
  '/specification/$id/grounding': typeof SpecificationIdViewGroundingRoute
  '/specification/$id/requirements-review': typeof SpecificationIdViewRequirementsReviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/specification/$id': typeof SpecificationIdRouteRouteWithChildren
  '/specification/$id/_view': typeof SpecificationIdViewRouteRouteWithChildren
  '/specification/$id/export': typeof SpecificationIdExportRoute
  '/specification/$id/': typeof SpecificationIdIndexRoute
  '/specification/$id/_view/acceptance-review': typeof SpecificationIdViewAcceptanceReviewRoute
  '/specification/$id/_view/elicitation': typeof SpecificationIdViewElicitationRoute
  '/specification/$id/_view/grounding': typeof SpecificationIdViewGroundingRoute
  '/specification/$id/_view/requirements-review': typeof SpecificationIdViewRequirementsReviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/specification/$id'
    | '/specification/$id/export'
    | '/specification/$id/'
    | '/specification/$id/acceptance-review'
    | '/specification/$id/elicitation'
    | '/specification/$id/grounding'
    | '/specification/$id/requirements-review'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/specification/$id'
    | '/specification/$id/export'
    | '/specification/$id/acceptance-review'
    | '/specification/$id/elicitation'
    | '/specification/$id/grounding'
    | '/specification/$id/requirements-review'
  id:
    | '__root__'
    | '/'
    | '/specification/$id'
    | '/specification/$id/_view'
    | '/specification/$id/export'
    | '/specification/$id/'
    | '/specification/$id/_view/acceptance-review'
    | '/specification/$id/_view/elicitation'
    | '/specification/$id/_view/grounding'
    | '/specification/$id/_view/requirements-review'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SpecificationIdRouteRoute: typeof SpecificationIdRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/specification/$id': {
      id: '/specification/$id'
      path: '/specification/$id'
      fullPath: '/specification/$id'
      preLoaderRoute: typeof SpecificationIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/specification/$id/': {
      id: '/specification/$id/'
      path: '/'
      fullPath: '/specification/$id/'
      preLoaderRoute: typeof SpecificationIdIndexRouteImport
      parentRoute: typeof SpecificationIdRouteRoute
    }
    '/specification/$id/export': {
      id: '/specification/$id/export'
      path: '/export'
      fullPath: '/specification/$id/export'
      preLoaderRoute: typeof SpecificationIdExportRouteImport
      parentRoute: typeof SpecificationIdRouteRoute
    }
    '/specification/$id/_view': {
      id: '/specification/$id/_view'
      path: ''
      fullPath: '/specification/$id'
      preLoaderRoute: typeof SpecificationIdViewRouteRouteImport
      parentRoute: typeof SpecificationIdRouteRoute
    }
    '/specification/$id/_view/requirements-review': {
      id: '/specification/$id/_view/requirements-review'
      path: '/requirements-review'
      fullPath: '/specification/$id/requirements-review'
      preLoaderRoute: typeof SpecificationIdViewRequirementsReviewRouteImport
      parentRoute: typeof SpecificationIdViewRouteRoute
    }
    '/specification/$id/_view/grounding': {
      id: '/specification/$id/_view/grounding'
      path: '/grounding'
      fullPath: '/specification/$id/grounding'
      preLoaderRoute: typeof SpecificationIdViewGroundingRouteImport
      parentRoute: typeof SpecificationIdViewRouteRoute
    }
    '/specification/$id/_view/elicitation': {
      id: '/specification/$id/_view/elicitation'
      path: '/elicitation'
      fullPath: '/specification/$id/elicitation'
      preLoaderRoute: typeof SpecificationIdViewElicitationRouteImport
      parentRoute: typeof SpecificationIdViewRouteRoute
    }
    '/specification/$id/_view/acceptance-review': {
      id: '/specification/$id/_view/acceptance-review'
      path: '/acceptance-review'
      fullPath: '/specification/$id/acceptance-review'
      preLoaderRoute: typeof SpecificationIdViewAcceptanceReviewRouteImport
      parentRoute: typeof SpecificationIdViewRouteRoute
    }
  }
}

interface SpecificationIdViewRouteRouteChildren {
  SpecificationIdViewAcceptanceReviewRoute: typeof SpecificationIdViewAcceptanceReviewRoute
  SpecificationIdViewElicitationRoute: typeof SpecificationIdViewElicitationRoute
  SpecificationIdViewGroundingRoute: typeof SpecificationIdViewGroundingRoute
  SpecificationIdViewRequirementsReviewRoute: typeof SpecificationIdViewRequirementsReviewRoute
}

const SpecificationIdViewRouteRouteChildren: SpecificationIdViewRouteRouteChildren =
  {
    SpecificationIdViewAcceptanceReviewRoute:
      SpecificationIdViewAcceptanceReviewRoute,
    SpecificationIdViewElicitationRoute: SpecificationIdViewElicitationRoute,
    SpecificationIdViewGroundingRoute: SpecificationIdViewGroundingRoute,
    SpecificationIdViewRequirementsReviewRoute:
      SpecificationIdViewRequirementsReviewRoute,
  }

const SpecificationIdViewRouteRouteWithChildren =
  SpecificationIdViewRouteRoute._addFileChildren(
    SpecificationIdViewRouteRouteChildren,
  )

interface SpecificationIdRouteRouteChildren {
  SpecificationIdViewRouteRoute: typeof SpecificationIdViewRouteRouteWithChildren
  SpecificationIdExportRoute: typeof SpecificationIdExportRoute
  SpecificationIdIndexRoute: typeof SpecificationIdIndexRoute
}

const SpecificationIdRouteRouteChildren: SpecificationIdRouteRouteChildren = {
  SpecificationIdViewRouteRoute: SpecificationIdViewRouteRouteWithChildren,
  SpecificationIdExportRoute: SpecificationIdExportRoute,
  SpecificationIdIndexRoute: SpecificationIdIndexRoute,
}

const SpecificationIdRouteRouteWithChildren =
  SpecificationIdRouteRoute._addFileChildren(SpecificationIdRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SpecificationIdRouteRoute: SpecificationIdRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
